### ISSUE TITLE
HMM Matrix & sequence import

### ISSUE THREAD

**Issue by Isson-N** [thierrygrimm/CpGIslandHMM#1]
Hello. I found your project on github, I'm not a programmer, but I need to find CpG islands using the HMM matrix. How can I use my matrix and insert a sequence about 15,000 nucleotides long?

**Comment by thierrygrimm** [comment]
The project is built in Jupyter (notebook), which is a interactive computing platform that contains live code, visualizations and text.

Your transition and emission matrix as well as initial probabilities can be manually put in (inline) under the section _Test Sequence_ found in [CpG islands Hidden Markov Model.ipynb](https://github.com/thierrygrimm/CpGIslandHMM/blob/ec4258de387e82d19103e426194dedc146aa19fd/Jupyter%20Notebooks/CpG%20islands%20Hidden%20Markov%20Model.ipynb)

![Section in question](https://user-images.githubusercontent.com/9351913/174279303-036f654e-9f33-4be0-b667-73e25c52f583.png)
The matrices are in the form of an array (inner square brackets represent the rows of your matrix).

Your individual sequence can be read from a .txt file by using the pandas module. It should then be assigned to the variable _test\_sequence_:
`test_sequence = pd.read_csv('mysequence.txt', header=None)[0][0]`


The more streamlined (alternative) version is by using Biopython (module import statements and more are necessary)
`SeqIO.parse(open(input_file),'fasta')`

**Comment by Isson-N** [comment]
Thank you very much! I will try.

пт, 17 июн. 2022 г., 13:36 Thierry ***@***.***>:
